version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
  backup_postgres_data: {}
  backup_postgres_data_backups: {}

services:
  postgres:
    image: postgres:9.0
    image: emr_api_local_postgres
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.postgres

  postgres_backup:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: postgres_backups
    container_name: postgres_backups
    depends_on:
      - postgres
    volumes:
      - backup_postgres_data_backups:/backups
    env_file:
      - ./.envs/.postgres
      - ./.envs/.aws
